name: Release Packages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Unplugged된 의존성을 설치하고 Yarn 파일들이 설치과정중에 변하지 않는지 확인해요. (만약 이 스텝에서 오류가 발생한다면 "yarn install"을 수행하고 커밋, 푸시하세요)
        run: |
          yarn install --immutable
        shell: bash

      - name: Create Release Pull Request or Publish to npm
        uses: cometkim/yarn-changeset-action@v1
        with:
          autoPublish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
